# Generated by Django 6.0.4 on 2026-06-11 11:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_review_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['name'], 'verbose_name': 'Actor', 'verbose_name_plural': 'Actors'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-release_year', 'title'], 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['price'], 'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AddField(
            model_name='actor',
            name='country_en',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='actor',
            name='country_ru',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='actor',
            name='country_uz',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='actor',
            name='gender_en',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='actor',
            name='gender_ru',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='actor',
            name='gender_uz',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre_en',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre_ru',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre_uz',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_en',
            field=models.CharField(db_index=True, max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_ru',
            field=models.CharField(db_index=True, max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_uz',
            field=models.CharField(db_index=True, max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_en',
            field=models.TextField(null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_ru',
            field=models.TextField(null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_uz',
            field=models.TextField(null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='title_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='birth_date',
            field=models.DateField(verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='country',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Release year'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.movie', verbose_name='Movie'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='duration',
            field=models.DurationField(help_text='For example: 30 days, 1 year', verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Title'),
        ),
        migrations.AddIndex(
            model_name='actor',
            index=models.Index(fields=['country_uz', 'name'], name='main_actor_country_be235e_idx'),
        ),
        migrations.AddIndex(
            model_name='actor',
            index=models.Index(fields=['country_ru', 'name'], name='main_actor_country_87fc7f_idx'),
        ),
        migrations.AddIndex(
            model_name='actor',
            index=models.Index(fields=['country_en', 'name'], name='main_actor_country_a44527_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title_uz'], name='main_movie_title_508b1f_idx-uz'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title_ru'], name='main_movie_title_508b1f_idx-ru'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title_en'], name='main_movie_title_508b1f_idx-en'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['genre_uz'], name='main_movie_genre_1e8c2c_idx-uz'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['genre_ru'], name='main_movie_genre_1e8c2c_idx-ru'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['genre_en'], name='main_movie_genre_1e8c2c_idx-en'),
        ),
    ]
